SELECT p.PRODUCT_CODE AS PRODUCT_CODE, SUM(p.PRICE * o.SALES_AMOUNT) AS SALES
FROM PRODUCT p INNER JOIN OFFLINE_SALE o
ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY p.product_id
ORDER BY SALES DESC, PRODUCT_CODE;